module.exports = {
    ID: "uuid",
    SORT: "sortkey",
    CONF_NAME: "name",
    CONF_DATE_FROM: "from",
    CONF_DATE_TO: "to",
    CONF_TOPICS: "topics",
    CONF_TALKS: "talks",
    CONF_LOCATION: "location",
    LOCATION_NAME: "name",
    LOCATION_ADDRESS: "address",
    TALK_FROM: "from",
    TALK_TO: "to",
    TALK_TOPICS: "topics",
    TALK_NAME: "name",
    TALK_ROOM: "room",
    ROOM_NAME: "name",
    ROOM_NAME_IN_LOCATION: "nameInLocation",
    TALK_SPEAKER: "speaker",
    SPEAKER_NAME: "name",
    SPEAKER_TITLE: "title",
    SPEAKER_COMPANY: "company",
};
